"use strict";

export let GUI_TX_TYPE = /*#__PURE__*/function (GUI_TX_TYPE) {
  GUI_TX_TYPE[GUI_TX_TYPE["NORMAL"] = 0] = "NORMAL";
  GUI_TX_TYPE[GUI_TX_TYPE["PUSH_OFFER"] = 1] = "PUSH_OFFER";
  GUI_TX_TYPE[GUI_TX_TYPE["UPDATE_OFFER"] = 2] = "UPDATE_OFFER";
  GUI_TX_TYPE[GUI_TX_TYPE["CANCEL_OFFER"] = 3] = "CANCEL_OFFER";
  GUI_TX_TYPE[GUI_TX_TYPE["NEW_ALIAS"] = 4] = "NEW_ALIAS";
  GUI_TX_TYPE[GUI_TX_TYPE["UPDATE_ALIAS"] = 5] = "UPDATE_ALIAS";
  GUI_TX_TYPE[GUI_TX_TYPE["COIN_BASE"] = 6] = "COIN_BASE";
  GUI_TX_TYPE[GUI_TX_TYPE["ESCROW_PROPOSAL"] = 7] = "ESCROW_PROPOSAL";
  GUI_TX_TYPE[GUI_TX_TYPE["ESCROW_TRANSFER"] = 8] = "ESCROW_TRANSFER";
  GUI_TX_TYPE[GUI_TX_TYPE["ESCROW_RELEASE_NORMAL"] = 9] = "ESCROW_RELEASE_NORMAL";
  GUI_TX_TYPE[GUI_TX_TYPE["ESCROW_RELEASE_BURN"] = 10] = "ESCROW_RELEASE_BURN";
  GUI_TX_TYPE[GUI_TX_TYPE["ESCROW_CANCEL_PROPOSAL"] = 11] = "ESCROW_CANCEL_PROPOSAL";
  GUI_TX_TYPE[GUI_TX_TYPE["ESCROW_RELEASE_CANCEL"] = 12] = "ESCROW_RELEASE_CANCEL";
  GUI_TX_TYPE[GUI_TX_TYPE["HTLC_DEPOSIT"] = 13] = "HTLC_DEPOSIT";
  GUI_TX_TYPE[GUI_TX_TYPE["HTLC_REDEEM"] = 14] = "HTLC_REDEEM";
  return GUI_TX_TYPE;
}({});
export let contract_state = /*#__PURE__*/function (contract_state) {
  contract_state[contract_state["proposal_sent"] = 1] = "proposal_sent";
  contract_state[contract_state["contract_accepted"] = 2] = "contract_accepted";
  contract_state[contract_state["contract_released_normal"] = 3] = "contract_released_normal";
  contract_state[contract_state["contract_released_burned"] = 4] = "contract_released_burned";
  contract_state[contract_state["contract_cancel_proposal_sent"] = 5] = "contract_cancel_proposal_sent";
  contract_state[contract_state["contract_released_cancelled"] = 6] = "contract_released_cancelled";
  return contract_state;
}({});
export let TX_SERVICE_ATTACHMENT = /*#__PURE__*/function (TX_SERVICE_ATTACHMENT) {
  /* eslint-disable no-bitwise */
  TX_SERVICE_ATTACHMENT[TX_SERVICE_ATTACHMENT["ENCRYPT_BODY"] = 1] = "ENCRYPT_BODY";
  TX_SERVICE_ATTACHMENT[TX_SERVICE_ATTACHMENT["DEFLATE_BODY"] = 2] = "DEFLATE_BODY";
  TX_SERVICE_ATTACHMENT[TX_SERVICE_ATTACHMENT["ENCRYPT_BODY_ISOLATE_AUDITABLE"] = 4] = "ENCRYPT_BODY_ISOLATE_AUDITABLE";
  TX_SERVICE_ATTACHMENT[TX_SERVICE_ATTACHMENT["ENCRYPT_ADD_PROOF"] = 8] = "ENCRYPT_ADD_PROOF";
  /* eslint-enable no-bitwise */
  return TX_SERVICE_ATTACHMENT;
}({});
export let ASSET_DESCRIPTOR_OPERATION_VERSION = /*#__PURE__*/function (ASSET_DESCRIPTOR_OPERATION_VERSION) {
  ASSET_DESCRIPTOR_OPERATION_VERSION[ASSET_DESCRIPTOR_OPERATION_VERSION["HF4_VER"] = 1] = "HF4_VER";
  ASSET_DESCRIPTOR_OPERATION_VERSION[ASSET_DESCRIPTOR_OPERATION_VERSION["HF5_VER"] = 2] = "HF5_VER";
  ASSET_DESCRIPTOR_OPERATION_VERSION[ASSET_DESCRIPTOR_OPERATION_VERSION["LAST_VER"] = 2] = "LAST_VER";
  return ASSET_DESCRIPTOR_OPERATION_VERSION;
}({});
export let ASSET_DESCRIPTOR_OPERATION_TYPE = /*#__PURE__*/function (ASSET_DESCRIPTOR_OPERATION_TYPE) {
  ASSET_DESCRIPTOR_OPERATION_TYPE[ASSET_DESCRIPTOR_OPERATION_TYPE["UNDEFINED"] = 0] = "UNDEFINED";
  ASSET_DESCRIPTOR_OPERATION_TYPE[ASSET_DESCRIPTOR_OPERATION_TYPE["REGISTER"] = 1] = "REGISTER";
  ASSET_DESCRIPTOR_OPERATION_TYPE[ASSET_DESCRIPTOR_OPERATION_TYPE["EMIT"] = 2] = "EMIT";
  ASSET_DESCRIPTOR_OPERATION_TYPE[ASSET_DESCRIPTOR_OPERATION_TYPE["UPDATE"] = 3] = "UPDATE";
  ASSET_DESCRIPTOR_OPERATION_TYPE[ASSET_DESCRIPTOR_OPERATION_TYPE["PUBLIC_BURN"] = 4] = "PUBLIC_BURN";
  return ASSET_DESCRIPTOR_OPERATION_TYPE;
}({});
export let BASIC_RESPONSE_STATUS = /*#__PURE__*/function (BASIC_RESPONSE_STATUS) {
  BASIC_RESPONSE_STATUS["OK"] = "OK";
  BASIC_RESPONSE_STATUS["BUSY"] = "BUSY";
  BASIC_RESPONSE_STATUS["NOT_FOUND"] = "NOT_FOUND";
  BASIC_RESPONSE_STATUS["FAILED"] = "FAILED";
  return BASIC_RESPONSE_STATUS;
}({});
export let API_RETURN_CODE = /*#__PURE__*/function (API_RETURN_CODE) {
  API_RETURN_CODE["OK"] = "OK";
  API_RETURN_CODE["FAIL"] = "FAILED";
  API_RETURN_CODE["NOT_FOUND"] = "NOT_FOUND";
  API_RETURN_CODE["ACCESS_DENIED"] = "ACCESS_DENIED";
  API_RETURN_CODE["INTERNAL_ERROR"] = "INTERNAL_ERROR";
  API_RETURN_CODE["NOT_ENOUGH_MONEY"] = "NOT_ENOUGH_MONEY";
  API_RETURN_CODE["NOT_ENOUGH_OUTPUTS_FOR_MIXING"] = "NOT_ENOUGH_OUTPUTS_FOR_MIXING";
  API_RETURN_CODE["INTERNAL_ERROR_QUE_FULL"] = "INTERNAL_ERROR_QUE_FULL";
  API_RETURN_CODE["BAD_ARG"] = "BAD_ARG";
  API_RETURN_CODE["BAD_ARG_EMPTY_DESTINATIONS"] = "BAD_ARG_EMPTY_DESTINATIONS";
  API_RETURN_CODE["BAD_ARG_WRONG_FEE"] = "BAD_ARG_WRONG_FEE";
  API_RETURN_CODE["BAD_ARG_INVALID_ADDRESS"] = "BAD_ARG_INVALID_ADDRESS";
  API_RETURN_CODE["BAD_ARG_WRONG_AMOUNT"] = "BAD_ARG_WRONG_AMOUNT";
  API_RETURN_CODE["BAD_ARG_UNKNOWN_DECIMAL_POINT"] = "BAD_ARG_UNKNOWN_DECIMAL_POINT";
  API_RETURN_CODE["BAD_ARG_WRONG_PAYMENT_ID"] = "BAD_ARG_WRONG_PAYMENT_ID";
  API_RETURN_CODE["BAD_ARG_INVALID_JSON"] = "BAD_ARG_INVALID_JSON";
  API_RETURN_CODE["WRONG_PASSWORD"] = "WRONG_PASSWORD";
  API_RETURN_CODE["WALLET_WRONG_ID"] = "WALLET_WRONG_ID";
  API_RETURN_CODE["WALLET_WATCH_ONLY_NOT_SUPPORTED"] = "WALLET_WATCH_ONLY_NOT_SUPPORTED";
  API_RETURN_CODE["WALLET_AUDITABLE_NOT_SUPPORTED"] = "WALLET_AUDITABLE_NOT_SUPPORTED";
  API_RETURN_CODE["WALLET_FEE_TOO_LOW"] = "API_RETURN_CODE_WALLET_FEE_TOO_LOW";
  API_RETURN_CODE["FILE_NOT_FOUND"] = "FILE_NOT_FOUND";
  API_RETURN_CODE["ALREADY_EXISTS"] = "ALREADY_EXISTS";
  API_RETURN_CODE["CANCELED"] = "CANCELED";
  API_RETURN_CODE["FILE_RESTORED"] = "FILE_RESTORED";
  API_RETURN_CODE["TRUE"] = "TRUE";
  API_RETURN_CODE["FALSE"] = "FALSE";
  API_RETURN_CODE["CORE_BUSY"] = "CORE_BUSY";
  API_RETURN_CODE["OVERFLOW"] = "OVERFLOW";
  API_RETURN_CODE["BUSY"] = "BUSY";
  API_RETURN_CODE["INVALID_FILE"] = "INVALID_FILE";
  API_RETURN_CODE["WRONG_SEED"] = "WRONG_SEED";
  API_RETURN_CODE["GENESIS_MISMATCH"] = "GENESIS_MISMATCH";
  API_RETURN_CODE["DISCONNECTED"] = "DISCONNECTED";
  API_RETURN_CODE["UNINITIALIZED"] = "UNINITIALIZED";
  API_RETURN_CODE["TX_IS_TOO_BIG"] = "TX_IS_TOO_BIG";
  API_RETURN_CODE["TX_REJECTED"] = "TX_REJECTED";
  API_RETURN_CODE["HTLC_ORIGIN_HASH_MISSMATCHED"] = "HTLC_ORIGIN_HASH_MISSMATCHED";
  API_RETURN_CODE["WRAP"] = "WRAP";
  API_RETURN_CODE["MISSING_ZC_INPUTS"] = "MISSING_ZC_INPUTS";
  API_RETURN_CODE["ARG_OUT_OF_LIMITS"] = "ARG_OUT_OF_LIMITS";
  API_RETURN_CODE["TX_HAS_TOO_MANY_OUTPUTS"] = "TX_HAS_TOO_MANY_OUTPUTS";
  API_RETURN_CODE["TX_HAS_TOO_MANY_INPUTS"] = "TX_HAS_TOO_MANY_INPUTS";
  return API_RETURN_CODE;
}({});
export let JSON_RPC_ERROR_CODE = /*#__PURE__*/function (JSON_RPC_ERROR_CODE) {
  // -32000 to -32099 : Reserved for implementation-defined server-errors.
  /** [usage](../libraries/Zano/contrib/epee/include/net/http_server_handlers_map2.h#416) */
  JSON_RPC_ERROR_CODE[JSON_RPC_ERROR_CODE["DEFAULT"] = -32000] = "DEFAULT";
  /**
   * [usage]{@link file://./../libraries/Zano/contrib/epee/include/net/http_server_handlers_map2.h#L416}
   */
  JSON_RPC_ERROR_CODE[JSON_RPC_ERROR_CODE["INVALID_REQUEST"] = -32600] = "INVALID_REQUEST";
  /**
   * [definition]{@link file://./../libraries/Zano/src/stratum/stratum_server.cpp#L68}
   * [usage]{@link file://./../libraries/Zano/contrib/epee/include/net/http_server_handlers_map2.h#L403}
   */
  JSON_RPC_ERROR_CODE[JSON_RPC_ERROR_CODE["METHOD_NOT_FOUND"] = -32601] = "METHOD_NOT_FOUND";
  /**
   * [usage]{@link file://./../libraries/Zano/contrib/epee/include/net/http_server_handlers_map2.h#L435}
   */
  JSON_RPC_ERROR_CODE[JSON_RPC_ERROR_CODE["INVALID_PARAMS"] = -32602] = "INVALID_PARAMS";
  /**
   * [usage]{@link file://./../libraries/Zano/contrib/epee/include/net/http_server_handlers_map2.h#L501}
   */
  JSON_RPC_ERROR_CODE[JSON_RPC_ERROR_CODE["INTERNAL_ERROR"] = -32603] = "INTERNAL_ERROR";
  /**
   * [definition]{@link file://./../libraries/Zano/src/stratum/stratum_server.cpp#L69}
   * [usage]{@link file://./../libraries/Zano/contrib/epee/include/net/http_server_handlers_map2.h#L537}
   */
  JSON_RPC_ERROR_CODE[JSON_RPC_ERROR_CODE["PARSE_ERROR"] = -32700] = "PARSE_ERROR";
  return JSON_RPC_ERROR_CODE;
}({});
export let WALLET_RPC_ERROR_CODE = /*#__PURE__*/function (WALLET_RPC_ERROR_CODE) {
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["UNKNOWN_ERROR"] = -1] = "UNKNOWN_ERROR";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["WRONG_ADDRESS"] = -2] = "WRONG_ADDRESS";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["DAEMON_IS_BUSY"] = -3] = "DAEMON_IS_BUSY";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["GENERIC_TRANSFER_ERROR"] = -4] = "GENERIC_TRANSFER_ERROR";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["WRONG_PAYMENT_ID"] = -5] = "WRONG_PAYMENT_ID";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["WRONG_ARGUMENT"] = -6] = "WRONG_ARGUMENT";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["NOT_ENOUGH_MONEY"] = -7] = "NOT_ENOUGH_MONEY";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["WRONG_MIXINS_FOR_AUDITABLE_WALLET"] = -8] = "WRONG_MIXINS_FOR_AUDITABLE_WALLET";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["GENERIC_ERROR"] = -9] = "GENERIC_ERROR";
  WALLET_RPC_ERROR_CODE[WALLET_RPC_ERROR_CODE["KEY_IMAGE_ALREADY_SPENT"] = -10] = "KEY_IMAGE_ALREADY_SPENT";
  return WALLET_RPC_ERROR_CODE;
}({});
export let wallet_state = /*#__PURE__*/function (wallet_state) {
  wallet_state[wallet_state["initial"] = 0] = "initial";
  wallet_state[wallet_state["synchronizing"] = 1] = "synchronizing";
  wallet_state[wallet_state["ready"] = 2] = "ready";
  wallet_state[wallet_state["error"] = 3] = "error";
  return wallet_state;
}({});
export let CORE_RPC_ERROR_CODE = /*#__PURE__*/function (CORE_RPC_ERROR_CODE) {
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["WRONG_PARAM"] = -1] = "WRONG_PARAM";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["TOO_BIG_HEIGHT"] = -2] = "TOO_BIG_HEIGHT";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["TOO_BIG_RESERVE_SIZE"] = -3] = "TOO_BIG_RESERVE_SIZE";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["WRONG_WALLET_ADDRESS"] = -4] = "WRONG_WALLET_ADDRESS";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["INTERNAL_ERROR"] = -5] = "INTERNAL_ERROR";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["WRONG_BLOCKBLOB"] = -6] = "WRONG_BLOCKBLOB";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["BLOCK_NOT_ACCEPTED"] = -7] = "BLOCK_NOT_ACCEPTED";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["CORE_BUSY"] = -9] = "CORE_BUSY";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["INVALID_ALIAS_NAME"] = -10] = "INVALID_ALIAS_NAME";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["INVALID_ALIAS_ADDRESS"] = -11] = "INVALID_ALIAS_ADDRESS";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["ALIAS_COMMENT_TO_LONG"] = -12] = "ALIAS_COMMENT_TO_LONG";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["BLOCK_ADDED_AS_ALTERNATIVE"] = -13] = "BLOCK_ADDED_AS_ALTERNATIVE";
  CORE_RPC_ERROR_CODE[CORE_RPC_ERROR_CODE["NOT_FOUND"] = -14] = "NOT_FOUND";
  return CORE_RPC_ERROR_CODE;
}({});
export let daemon_network_state = /*#__PURE__*/function (daemon_network_state) {
  daemon_network_state[daemon_network_state["connecting"] = 0] = "connecting";
  daemon_network_state[daemon_network_state["synchronizing"] = 1] = "synchronizing";
  daemon_network_state[daemon_network_state["online"] = 2] = "online";
  daemon_network_state[daemon_network_state["loading_core"] = 3] = "loading_core";
  daemon_network_state[daemon_network_state["internal_error"] = 4] = "internal_error";
  daemon_network_state[daemon_network_state["unloading_core"] = 5] = "unloading_core";
  daemon_network_state[daemon_network_state["downloading_database"] = 6] = "downloading_database";
  return daemon_network_state;
}({});
export let RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS = /*#__PURE__*/function (RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS) {
  RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS[RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS["COINBASE"] = 1] = "COINBASE";
  RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS[RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS["NOT_ALLOWED"] = 2] = "NOT_ALLOWED";
  RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS[RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS["POS_COINBASE"] = 4] = "POS_COINBASE";
  return RANDOM_OUTPUTS_FOR_AMOUNTS_FLAGS;
}({});
//# sourceMappingURL=entities.js.map