name: CI
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepare
      - name: Store package
        uses: actions/upload-artifact@v4
        with:
          name: zano-wallet
          path: |
            artifacts/zano-wallet-*.apk
          retention-days: 3
